Backend/Program.cs
=> Testing Pull Request

Backend.Test/CategoryTests.cs, Backend.Test/GlobalUsings.cs, Backend/DAL/CategoryManager.cs, Backend/GlobalUsings.cs
- [ X ] Communication: I've discussed this with core contributors lready. If work hasn't been agreed, this work might be rejected 
Describe the PR here
=> Added globalUsings and created tests for category

Backend.Test/BudgetTests.cs, Backend/DAL/BudgetManager.cs, Backend/Helpers/BudgetFiller.cs, Backend/Models/Budget.cs
Added some tests and logics for them
=> added budget tests and logics

frontend/package-lock.json, frontend/package.json
=> Added a components-folder

Backend.Test/BudgetTests.cs, Backend.Test/CategoryTests.cs, Backend/DAL/BudgetManager.cs, Backend/DAL/CategoryManager.cs
=> Category tests and Logics

Backend/Controllers/BudgetController.cs, Backend/DAL/BudgetManager.cs, Backend/Helpers/BudgetFiller.cs, Backend/Models/Category.cs, Backend/Models/Item.cs, Backend/Program.cs, frontend/src/App.svelte, frontend/src/Components/FetchBudget.svelte
=> Mattias feature

Backend/Helpers/BudgetFiller.cs, Backend/Models/Category.cs, Backend/Models/Item.cs, Backend/Program.cs, frontend/src/Components/FetchBudget.svelte, frontend/src/lib/Counter.svelte, frontend/src/main.js
We had trouble displaying data in frontend from API. "solved" the first issues and now we can start display the data that we want.
=> Fetched data from API and display in frontend. "fixed" policy in program.cs

frontend/src/Components/FetchBudget.svelte
Added more code for FE, created objects/arrays that we can use to display data
=> display budget in frontend

Backend/Helpers/BudgetFiller.cs
=> missed a file in backend

Backend/DAL/ItemManager.cs, Backend/Helpers/BudgetFiller.cs
=> Added items to smallBudget

frontend/src/Components/Expences.svelte
start of rendering new field in budget display
=> new field in budget 

Backend/Controllers/BudgetController.cs, frontend/src/Components/Accordion.svelte, frontend/src/Components/Expences.svelte, frontend/src/Components/FetchBudget.svelte
Send budget to backend done
Added code in frontend so we can send budget to API backend
=> Can send budget to backend. Now we need to handle it accordingly

frontend/src/Components/Accordion.svelte
added calculation, need to split up in different components.
=> calculate totalamount frontend

frontend/public/app.css, frontend/src/App.svelte, frontend/src/Components/Accordion.svelte, frontend/src/Components/FetchBudget.svelte, frontend/src/Components/Nav.svelte
=> More CSS, added wrapper and fullbleed vars

Backend.Test/BudgetTests.cs, Backend.Test/CategoryTests.cs, Backend.Test/ItemTests.cs, Backend/Controllers/BudgetController.cs, Backend/DAL/BudgetManager.cs, Backend/DAL/CategoryManager.cs, Backend/DAL/ItemManager.cs, frontend/src/App.svelte
added some futures to backend to handle the new budgetsystem. Some changes to tests aswell
=> Change tests to fit new budgetHandling from frontend

Backend.Test/BudgetTests.cs, Backend/Helpers/BudgetFiller.cs
=> BudgetTemplates in B-E

frontend/public/app.css, frontend/src/Components/Accordion.svelte
=> Jesper feature

frontend/src/Components/Accordion.svelte, frontend/src/Components/FetchLatestId.svelte
added small function for handling itemIds
=> Added component to handle latest Id of item

Backend.Test/ItemTests.cs, Backend/DAL/BudgetManager.cs, Backend/DAL/CategoryManager.cs, Backend/DAL/ItemManager.cs
start to check if the budget is valid in backend
=> backend start of handle the budget sent from FE

frontend/src/App.svelte, frontend/src/Components/Accordion.svelte, frontend/src/Components/Nav.svelte
added function to name your budget and set to budgetprop FE
Describe the PR here
=> added function to name your budget and set to budgetprop FE

frontend/src/Components/Accordion.svelte, frontend/src/Components/Functions/FetchLatestCategoryId.svelte
- [] Tests: Added/updated and all pass
Added frontend logic to removal and adding of new categories, still encountering some issues with removing all existing categories and then adding a new one (auto resets to template). Have to figure it out!
=> Category functionality and removal of {#key}

frontend/src/App.svelte, frontend/src/Components/Accordion.svelte, frontend/src/Components/Income.svelte
fixed the functionality of Income, need to style and place it accordingly
=> fixed income to be placed at app, now we need to do the css

frontend/public/app.css, frontend/src/App.svelte, frontend/src/Components/Accordion.svelte, frontend/src/Components/Button.svelte, frontend/src/Components/Income.svelte, frontend/src/Components/Nav.svelte
=> looking at base structure of nav and our app.svelte

Backend.Test/CategoryTests.cs, Backend.Test/Data/CategoryTestData.cs, Backend.Test/Fixtures/CategoryFixture.cs
=> added CategoryTestData classes with data also

Backend.Test/CategoryTests.cs, Backend.Test/Data/CategoryTestData.cs, Backend.Test/Data/ItemTestData.cs, Backend.Test/ItemTests.cs, Backend/DAL/CategoryManager.cs, Backend/DAL/ItemManager.cs, Backend/Interfaces/ICategoryManager.cs
Added some more test in line with recent changes
=> added tests to category and modified the manager abit

Backend/Controllers/BudgetController.cs
Added small if statement around get controller.
=> small null reference security in controller

Source/Backend.Api/Controllers/BudgetController.cs, Source/Backend.Api/DAL/BudgetManager.cs, Source/Backend.Api/Helpers/PDFGenerator.cs, Source/Backend.Api/Program.cs, Source/Backend.Core/Interfaces/IBudget.cs, Source/Backend.Core/Interfaces/IBudgetManager.cs, Source/Backend.Core/Models/Budget.cs, frontend/src/Components/ContentRight.svelte
=> Added fields to document and started adding some security features

Source/Backend.Api/Helpers/PDFGenerator.cs, frontend/src/Components/ContentRight.svelte
=> polished document for purpose and changed name and button-text

Source/Backend.Api/Helpers/PDFGenerator.cs
=> small tweaks to the document

frontend/package.json, package.json
=> some shizzle

frontend/package.json
=> changed build to svelte-kit build

Source/Backend.Core/Models/Item.cs, Tests/Backend.UnitTest/BudgetTests.cs, frontend/public/app.css, frontend/src/App.svelte, frontend/src/Components/Accordion.svelte, frontend/src/Components/ContentRight.svelte, frontend/src/Components/Income.svelte
Small tweeks for user experience
=> small tweeks 

frontend/src/Components/ContentRight.svelte
Change to error message so button doen't move
=> change to error msg

Source/Backend.Api/DAL/BudgetManager.cs
Implemented a own method for trimming the budget names
=> added trim method for budget manager

Source/Backend.Api/Controllers/BudgetController.cs, Source/Backend.Api/DAL/BudgetManager.cs, Source/Backend.Api/DAL/CategoryManager.cs, Source/Backend.Api/DAL/ItemManager.cs, Source/Backend.Api/Helpers/PDFGenerator.cs, Source/Backend.Core/Interfaces/IBudgetManager.cs, Source/Backend.Core/Interfaces/ICategoryManager.cs, Source/Backend.Core/Interfaces/IItemManager.cs, Source/Backend.Core/Interfaces/IPdfService.cs, Tests/Backend.UnitTest/BudgetTests.cs, Tests/Backend.UnitTest/CategoryTests.cs, Tests/Backend.UnitTest/ItemTests.cs
Coded towards Interfaces instead of hardcode against budget
=> Coded towards interfaces to have more seams in code
